[main]

token = ""
port = 7942
hmac_key = ""
buildbot_key = ""
oauth_client_id = ""
oauth_client_secret = ""

[[repo]]

owner = ""
repo = ""

reviewers = ["barosl"]
buildbot_url = ""
builders = ["auto-linux", "auto-mac"]
try_builders = ["try-linux", "try-mac"]

master_branch = "master"
buildbot_branch = "auto"
buildbot_try_branch = "try"
tmp_branch = "tmp"
rollup_branch = "rollup"

buildbot_username = ""
buildbot_password = ""

travis_token = ""
