[github]

access_token = ""

app_client_id = ""
app_client_secret = ""

[web]

port = 54856

[repo.test]

owner = ""
name = ""

reviewers = ["barosl", "graydon"]

#[repo.test.branch]
#
#master = "master"
#auto = "auto"
#try = "try"
#tmp = "tmp"
#rollup = "rollup"

[repo.test.github]

secret = ""

#[repo.test.buildbot]
#
#url = ""
#secret = ""
#
#builders = ["auto-linux", "auto-mac"]
#try_builders = ["try-linux", "try-mac"]
#
#username = ""
#password = ""

#[repo.test.travis]
#
#token = ""
